# Generated by Django 3.2.9 on 2021-11-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Должность')),
                ('hire_data', models.DateTimeField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Размер заработной платы')),
                ('paid_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Информация о выплаченной зарплате')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
