# Generated by Django 3.2.9 on 2021-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='ФИО'),
        ),
    ]
